name: Build and Upload FINA Binaries

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [
          x86_64, x86_64-static,
          i686, i686-static,
          arm, arm-static,
          aarch64, aarch64-static,
          powerpc, powerpc-static,
          cosmo
          ]
      fail-fast: true

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v15

      - name: Build and Create ZIP Archive
        run: |
          nix build .#${{ matrix.target }}
          cp -rP result fina-${{ matrix.target }}
          tar cvfz fina-${{ matrix.target }}.tar.gz fina-${{ matrix.target }}

      - name: Upload ZIP Files as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fina-binaries
          path: *.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v15

      - name: Create GitHub Release
        uses: gh-actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: *.tar.gz
